### ISSUE TITLE
Add ResultBuilder-backed API for subview distribution

### ISSUE THREAD

**Issue by dfed** [square/Paralayout#116]
Paralayout's `applyVerticalSubviewDistribution` and `applyHorizontalSubviewDistribution` methods are incredibly powerful. Adding a [result builder](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/advancedoperators#Result-Builders) could make the code that creates these distributions more expressive.

In the simplest of cases, utilizing a distribution builder would enable removing the need to declare an array. Taking us from:

```swift
containerView.applyVerticalSubviewDistribution(
    [
        1.flexible,
        titleLabel,
        16.fixed,
        bodyLabel,
        16.fixed,
        actionButton,
        1.flexible,
    ]
)
```

to:

```swift
containerView.applyVerticalSubviewDistribution {
    1.flexible
    titleLabel
    16.fixed
    bodyLabel
    16.fixed
    actionButton
    1.flexible
}
```

But that's just the beginning. Since result builders allow for inline `if` statements, they'd enable writing distribution like:

```swift
containerView.applyVerticalSubviewDistribution {
    1.flexible
    titleLabel
    if bodyLabel.hasText {
        16.fixed
        bodyLabel
    }
    16.fixed
    actionButton
    1.flexible
}
```

Result builders also enable inlining for loop and if-else statements, enabling consumers to inline complex distributions. The benefits here purely syntactic – there'd be zero changes required to the underlying Paralayout library. The only additions would be:

1. A `@resultbuilder public struct ViewDistributionBuilder` type.
1. A `applyVerticalSubviewDistribution` method that takes a `@ViewDistributionBuilder _ distribution: () -> [ViewDistributionSpecifying]` closure rather than a `_ distribution: [ViewDistributionSpecifying]` argument. This new method would call through to the existing `applyVerticalSubviewDistribution` method.
1. A `applyHorizontalSubviewDistribution` method that takes a `@ViewDistributionBuilder _ distribution: () -> [ViewDistributionSpecifying]` closure rather than a `_ distribution: [ViewDistributionSpecifying]` argument. This new method would call through to the existing `applyVerticalSubviewDistribution` method.

Result builders [were introduced in Swift 5.4](https://www.swift.org/blog/swift-5.4-released/), so this functionality would only be added for consumers using Swift 5.4 and above. I'd be happy to put up a PR that accomplishes this – I recently [did something similar in another view layout library](https://github.com/dfed/Relativity/pull/26).

**Comment by NickEntin** [comment]
Sounds great! Love the inline if example 🙌
