### ISSUE TITLE
Consider better name for cases in TargetAlignmentBehavior

### ISSUE THREAD

**Issue by NickEntin** [square/Paralayout#73]
We introduced a `TargetAlignmentBehavior` enum in #72 to control how views are aligned, in order to address the issues raised around aligning to scroll views in #54. The case names right now are a bit confusing, and I think we can do better, but I'm not sure what would be the clearest naming.

**Comment by NickEntin** [comment]
I wonder if it would be better to name these based on which coordinate space it's using. Something like:

```swift
/// Align to the position in the target view's superview's coordinate space, i.e. align to the target view's
/// bounds ignoring any origin offset. This is most commonly used when aligning sibling views in a hierarchy.
case targetSuperviewCoordinateSpace

/// Align to the position in the target view's coordinate space, i.e. align to the target view's bounds
/// including any origin offset. This is most commonly used when the target view is in the receiver's
/// superview chain.
case targetCoordinateSpace
```

**Comment by cocoalabs** [comment]
Should we drop the "target" prefix?

**Comment by NickEntin** [comment]
I agree that repeating "target" in the enum case and case names feels repetitive, but I _think_ it's correct when you read it out as a sentence.

```swift
sourceView.align(.rightCenter, to: targetView, .leftCenter, targetAlignmentBehavior: .targetSuperviewCoordinateSpace)
```

> Align the source view's right center position to the *target view*'s left center position in the **target view's superview's coordinate space**.

The "target" in the enum name says you're controlling how the _target_ view's position is calculated. The "target" in the case name tells you which view's superview we're talking about.

Maybe I'm overcomplicating this? But I think when you write in out in a sentence like that it makes sense.

**Comment by cocoalabs** [comment]
That's a valid point. Perhaps we could change the parameter name to `targeting:`
