### ISSUE TITLE
Converge on consistent preposition for describing alignment target

### ISSUE THREAD

**Issue by NickEntin** [square/Paralayout#79]
We currently use a mix of "with" and "to" when talking about alignment.

The base method and most parameterized usages use "with:"

* `align(.center, with: view, .center)`
* `align(.center, withSuperviewPosition: .center)`

But the superview methods use "to:"

* `alignToSuperview(.center, offset: .zero)`
* `alignToSuperview(.center, inset: 42)`

I feel strongly that we should converge on a single preposition to use in all of these cases, but I could be convinced to go with either one. I'm leaning towards "with," but curious is anyone else feels strongly.

**Comment by AliceAponasko** [comment]
How about renaming these
```
alignToSuperview(.center, offset: .zero)
alignToSuperview(.center, inset: 42)
```
to 
```
align(withSuperview: .center, offset: .zero)
align(withSuperview: .center, inset: 42)
```
